#!/bin/bash
#
# Get DNS resolution times for a list of domains

domains=(
    "www.google.com"
    "www.facebook.com"
    "www.instagram.com"
)

get_dns_resolution_time(){
    dig $domain | awk '/Query time/ {print $4}'
}

for domain in "${domains[@]}"
do
  resolution_time=$(get_dns_resolution_time $domain)
  echo "The DNS resolution time for $domain is $resolution_time ms"
    

done